

export const DOCTEUR_LOAD = "DOCTEUR_LOAD"
export const DOCTEUR_SUCC = "DOCTEUR_SUCC"
export const DOCTEUR_FAIL = "DOCTEUR_FAIL"

export const DOCTEUR_LOGOUT = "DOCTEUR_LOGOUT"

export const GET_DOCTEURS_LOAD = "GET_DOCTEURS_LOAD";
export const GET_DOCTEURS_SUCC = "GET_DOCTEURS_SUCC";
export const GET_DOCTEURS_FAIL = "GET_DOCTEURS_FAIL";
