export const DOCTEUR_LOAD = "DOCTEUR_LOAD";
export const DOCTEUR_SUCC = "DOCTEUR_SUCC";
export const DOCTEUR_FAIL = "DOCTEUR_FAIL";

export const DOCTEUR_LOGOUT = "DOCTEUR_LOGOUT";

export const GET_DOCTEURS_LOAD = "GET_DOCTEURS_LOAD";
export const GET_DOCTEURS_SUCC = "GET_DOCTEURS_SUCC";
export const GET_DOCTEURS_FAIL = "GET_DOCTEURS_FAIL";

export const GET_DOCTEUR_LOAD = "GET_DOCTEUR_LOAD";
export const GET_DOCTEUR_SUCC = "GET_DOCTEUR_SUCC";
export const GET_DOCTEUR_FAIL = "GET_DOCTEUR_FAIL";

export const CURRENT_DOCTEUR = "CURRENT_DOCTEUR";

export const EDIT_DOCTEUR_FAIL = "EDIT_DOCTEUR_FAIL";
export const EDIT_DOCTEUR_SUCC = "EDIT_DOCTEUR_SUCC";

export const DELETE_DOCTEUR_SUCC = "DELETE_DOCTEUR_SUCC";
export const DELETE_DOCTEUR_FAIL = "DELETE_DOCTEUR_FAIL";
