export const ADD_RENDEZVOUS_SUCC = "ADD_RENDEZVOUS_SUCC";
export const ADD_RENDEZVOUS_FAIL = "ADD_RENDEZVOUS_FAIL";

export const GET_RENDEZVOUS_LOAD = "GET_RENDEZVOUS_LOAD";
export const GET_RENDEZVOUS_SUCC = "GET_RENDEZVOUS_SUCC";
export const GET_RENDEZVOUS_FAIL = "GET_RENDEZVOUS_FAIL";

export const EDIT_RENDEZVOUS_SUCC = "EDIT_RENDEZVOUS_SUCC";
export const EDIT_RENDEZVOUS_FAIL = "EDIT_RENDEZVOUS_FAIL";
