export const ADD_RENDEZVOUS_SUCC = "ADD_RENDEZVOUS_SUCC";
export const ADD_RENDEZVOUS_FAIL = "ADD_RENDEZVOUS_FAIL";

export const DOCTEUR_RENDEZVOUS_LOAD = "DOCTEUR_RENDEZVOUS_LOAD";
export const DOCTEUR_RENDEZVOUS_SUCC = "DOCTEUR_RENDEZVOUS_SUCC";
export const DOCTEUR_RENDEZVOUS_FAIL = "DOCTEUR_RENDEZVOUS_FAIL";

export const PATIENT_RENDEZVOUS_LOAD = "PATIENT_RENDEZVOUS_LOAD";
export const PATIENT_RENDEZVOUS_SUCC = "PATIENT_RENDEZVOUS_SUCC";
export const PATIENT_RENDEZVOUS_FAIL = "PATIENT_RENDEZVOUS_FAIL";

export const EDIT_RENDEZVOUS_SUCC = "EDIT_RENDEZVOUS_SUCC";
export const EDIT_RENDEZVOUS_FAIL = "EDIT_RENDEZVOUS_FAIL";
