

export const PATIENT_LOAD = "PATIENT_LOAD"
export const PATIENT_SUCC = "PATIENT_SUCC"
export const PATIENT_FAIL = "PATIENT_FAIL"

export const PATIENT_LOGOUT = "PATIENT_LOGOUT"

export const CURRENT_PATIENT = "CURRENT_PATIENT";
